### PR TITLE
1. move "bn folding" and "prepack conv weight" to the hooked jit scri…

### PR DESCRIPTION
**Pull request by chunyuan-w**
…pt function 2. add check on fused node in the graph

1. For jit, the users no longer need to write the following code:
 ```python
 torch._C._jit_set_profiling_mode(False)
 torch._C._jit_set_profiling_executor(False)
 scripted = wrap_cpp_module(torch._C._jit_pass_fold_convbn(scripted._c))
 scripted = wrap_cpp_module(core._jit_prepack_conv_weight(scripted._c))
 ``` 
 These have been moved to the hooked torch.jit.script function.

2. Check whether the expected fused node exists in the graph after the fusion pass.

### CODE REVIEW

**Comment by chunyuan-w** [comment]
@EikanWang @pinzhenx

**Comment by pinzhenx** [comment]
LGTM. Thanks

**Comment by jgong5** [comment]
PyTorch has profiling graph on by default? May I know what's the issue with profiling mode on?

**Comment by chunyuan-w** [comment]
PyTorch v1.5.0-rc3 has profiling mode on by default. When profiling mode is on, nodes like prim::profile or prim::BailOut may be inserted between OPs that we want to fuse. For the moment, our fusion pass hasn't taken those profiling or bailout nodes into consideration and it will only fuse adjacent OPs. As a result, our fusion pass will not merge OPs like conv and relu into conv_relu. @jgong5

**Comment by jgong5** [comment]
I suppose `prim::profile` or `prim::BailOut` is only util op that only exists before the graph has been profiled? Do these ops still exist after the graph is profiled?

**Comment by chunyuan-w** [comment]
When we run for the first time, the graph will be profiled and has `prim::profile` nodes in it. When the profiling is ready, the graph will go through the profiling optimization passes and the final graph will have `prim::BailOut` nodes in it.

**Comment by chunyuan-w** [comment]
In PyTorch, `guard_elimination.cpp` will eliminate redundant util nodes. The implementation hasn't covered all the operations. 

I have tried to add the case of `aten::conv2d` to remove the util op after this node. Now, with profiling mode on, `aten::conv2d` and `aten::relu_` can be fused to `ipex::conv2d_relu`:

```
graph(%self : __torch__.Conv2dRelu_Fixed,
      %x.1 : Tensor):
  %4 : int = prim::Constant[value=1]() # /home2/chunyuan/anaconda3/envs/env_ipex/lib/python3.7/site-packages/torch/nn/modules/conv.py:343:47
  %3 : int[] = prim::Constant[value=[1, 1]]()
  %2 : int[] = prim::Constant[value=[0, 0]]()
  %21 : int = prim::BailoutTemplate_0()
  %18 : Float(32, 3, 224, 224) = prim::BailOut[index=0](%21, %x.1, %self)
  %5 : __torch__.torch.nn.modules.conv.Conv2d = prim::GetAttr[name="conv"](%self)
  %6 : Tensor = prim::GetAttr[name="weight"](%5)
  %19 : Float(32, 3, 3, 3) = prim::BailOut[index=1](%21, %6, %5, %18)
  %7 : Tensor? = prim::GetAttr[name="bias"](%5)
  %22 : Float(32, 32, 222, 222) = ipex::conv2d_relu(%18, %19, %7, %3, %2, %3, %4)
  %20 : Float(32, 32, 222, 222) = prim::BailOut[index=2](%21, %22)
  return (%20)
with prim::BailoutTemplate_0 = graph(%self : __torch__.Conv2dRelu_Fixed,
      %x.1 : Tensor):
  %2 : Float(32, 3, 224, 224) = prim::BailOut[index=0](%x.1, %self)
  %3 : int[] = prim::Constant[value=[0, 0]]()
  %4 : int[] = prim::Constant[value=[1, 1]]()
  %5 : int = prim::Constant[value=1]() # /home2/chunyuan/anaconda3/envs/env_ipex/lib/python3.7/site-packages/torch/nn/modules/conv.py:343:47
  %6 : __torch__.torch.nn.modules.conv.Conv2d = prim::GetAttr[name="conv"](%self)
  %7 : Tensor = prim::GetAttr[name="weight"](%6)
  %8 : Float(32, 3, 3, 3) = prim::BailOut[index=1](%7, %6, %2)
  %9 : Tensor? = prim::GetAttr[name="bias"](%6)
  %10 : Float(32, 32, 222, 222) = aten::conv2d(%2, %8, %9, %4, %3, %4, %5) # /home2/chunyuan/anaconda3/envs/env_ipex/lib/python3.7/site-packages/torch/nn/modules/conv.py:345:15
  %result.1 : Tensor = aten::relu_(%10) # /home2/chunyuan/anaconda3/envs/env_ipex/lib/python3.7/site-packages/torch/nn/functional.py:1061:17
  %12 : Float(32, 32, 222, 222) = prim::BailOut[index=2](%result.1)
  return (%12)
```

The added code in `guard_elimination.cpp`:
```
diff --git a/torch/csrc/jit/passes/guard_elimination.cpp b/torch/csrc/jit/passes/guard_elimination.cpp
index 3be0d12..be9c810 100644
--- a/torch/csrc/jit/passes/guard_elimination.cpp
+++ b/torch/csrc/jit/passes/guard_elimination.cpp
@@ -313,6 +313,19 @@ struct GuardElimination {
             n->input(4)->node()->kind() == prim::Constant &&
             // check that the ceil_mode is constant
             n->input(5)->node()->kind() == prim::Constant;
+      case aten::conv2d:
+        return !n->input(0)->type()->expect<TensorType>()->isSummarized() &&
+            !n->input(1)->type()->expect<TensorType>()->isSummarized() &&
+            // skip bias
+            // !n->input(2)->type()->expect<TensorType>()->isSummarized() &&
+            // check that the stride is constant
+            n->input(3)->node()->kind() == prim::Constant &&
+            // check that the padding is constant
+            n->input(4)->node()->kind() == prim::Constant &&
+            // check that the dilation is constant
+            n->input(5)->node()->kind() == prim::Constant &&
+            // check that the groups is constant
+            n->input(6)->node()->kind() == prim::Constant;
       case aten::unsqueeze:
         // check that the dimension argument is constant
         return !n->input(0)->type()->expect<TensorType>()->isSummarized() &&
```

For linear+relu, `aten::linear` will be replaced by `torch_ipex::linear` in extension. We cannot add directly the `torch_ipex::linear` case in `guards_elimination.cpp`. 
One possible solution is to turn `torch_ipex::linear` into `aten::linear` right before entering JIT, add the `aten::linear` case in `guard_elimination.cpp` to remove the util op after it, and then add a custom pass to rewrite `aten::linear` into `torch_ipex::linear` before entering our fusion pass in order to fuse linear and relu. @jgong5

**Comment by pinzhenx** [comment]
The crux of the linear problem is that linear was not dispatched in the same way as convolution_overrideable, so that we have to replace Linear in python level, which leads to torch_ipex::linear showing up in the graph that is foreign to pytorch native jit system

**Pull request merged**
