### PR TITLE
modify dil OPs

### PR DESCRIPTION
**Pull request by jiayisunx**

### CODE REVIEW

**Comment by jiayisunx** [comment]
@EikanWang @pinzhenx

**Comment by jiayisunx** [comment]
@XiaobingSuper

**Comment by pinzhenx** [comment]
This PR looks good to me.

One concern is that if we implement prepacking for linear, that might break the contiguous assumption. Anyway, this contiguity check is necessary for now.

It would be better if you could extract the UT from BERT so that we can implement prepack in the future without breaking the model.

**Comment by EikanWang** [comment]
@jiayisunx , is it possible to add UT to cover it?

**Comment by jiayisunx** [comment]
> @jiayisunx , is it possible to add UT to cover it?
I can add a UT with same input shape, but it's hard to cover BERT situation completely.

**Comment by pinzhenx** [comment]
Only one case that fails the contiguity check (before this patch) is enough.

**Comment by jiayisunx** [comment]
> Only one case that fails the contiguity check (before this patch) is enough.

I have added CHECK_DNNL_OP_PRE_COND in dil_linear_backward_input and dil_linear_backward_weights

**Comment by pinzhenx** [comment]
@EikanWang please help merge it

**Pull request merged**
