### PR TITLE
fix jit script error on adaptive_avg_pool2d

### PR DESCRIPTION
**Pull request by chunyuan-w**
hook torch.adaptive_avg_pool2d instead of F.adaptive_avg_pool2d to fix jit script error on adaptive_avg_pool2d

### CODE REVIEW

**Comment by chunyuan-w** [comment]
@XiaobingSuper

**Comment by XiaobingSuper** [comment]
@EikanWang , please help merge it.

**Comment by XiaobingSuper** [comment]
@chunyuan-w , this PR will disable DNNL path, what a problem which you met before this change?

**Comment by pinzhenx** [comment]
We've already fixed it internally. Please check out the code in gitlab.

**Pull request merged**
