### PR TITLE
enable DNNL OPs(dil_gelu, dil_gelu_backward, dil_native_layer_norm, d…

### PR DESCRIPTION
**Pull request by jiayisunx**
…il_native_layer_norm_backward)

### CODE REVIEW

**Comment by jiayisunx** [comment]
@EikanWang @pinzhenx

**Comment by EikanWang** [comment]
Jiayi, I enabled BF16 lazy reorder in master, could you help to enable bf16 lazy reorder in the new dil OPs?

**Comment by EikanWang** [comment]
For BF16 lazy-reorder, we will only focus on inference within this quarter.

**Comment by jiayisunx** [comment]
I have enabled BF16 lazy reorder for GELU. And LayerNorm performance on BF16 is poor, so I think we could not enable this OP for now. @EikanWang

**Comment by EikanWang** [comment]
> I have enabled BF16 lazy reorder for GELU. And LayerNorm performance on BF16 is poor, so I think we could not enable this OP for now. @EikanWang

Does that mean the performance of BF16 layernorm is not as good as fp32 layernorm? If yes, @pinzhenx , could we submit an issue to the DNNL team?

**Comment by jiayisunx** [comment]
Yes, and I have submitted it to DNNL team.

**Pull request merged**
