### PR TITLE
Refine unit test case and write the shape meta info back to aten tensor when the tensor is reordered to public format

### PR DESCRIPTION
**Pull request by EikanWang**
1. Make sure all input tensors of DNNL OP are contiguous
2. Expose some DNNL interface to PyThon to check if a tensor is dil tensor for unit test
3. Fix the issue that didn't check if the tensor own whole storage
4. Write the shape meta info back to aten tensor if the tensor is reordered to public format

### CODE REVIEW

**Comment by EikanWang** [comment]
@pinzhenx

**Comment by EikanWang** [comment]
@hongzhen1 @XiaobingSuper @jiayisunx

**Comment by hongzhen1** [comment]
LGTM

**Comment by pinzhenx** [comment]
LGTM. Thanks

**Pull request merged**
