### PR TITLE
Fix bf16 move_ker bug

### PR DESCRIPTION
**Pull request by JianpingChen066**
To fix DLRM BF16 training error

### CODE REVIEW

**Comment by JianpingChen066** [comment]
@hongzhen1 @EikanWang please have a review on this, Thanks

**Comment by EikanWang** [comment]
LGTM

**Comment by EikanWang** [comment]
can this patch fix the issue: https://github.com/intel/intel-extension-for-pytorch/issues/26

**Comment by JianpingChen066** [comment]
yes

**Comment by wduo** [comment]
@EikanWang https://github.com/intel/intel-extension-for-pytorch/issues/192#issuecomment-963770449 . 
Looking forward to your reply.

**Pull request merged**
